// This file has been automatically generated by the Unreal Header Implementation tool

#include "Buildables/FGBuildableSignSupport.h"
#include "Components/SceneComponent.h"
#include "FGColoredInstanceMeshProxy.h"
#include "Hologram/FGSignPoleHologram.h"
#include "Net/UnrealNetwork.h"

AFGBuildableSignSupport::AFGBuildableSignSupport() : Super() {
	this->mPoleScale = FVector2D::ZeroVector;
	this->mHologramClass = AFGSignPoleHologram::StaticClass();
}
void AFGBuildableSignSupport::GetLifetimeReplicatedProps(TArray< FLifetimeProperty >& OutLifetimeProps) const {
	Super::GetLifetimeReplicatedProps(OutLifetimeProps);
	DOREPLIFETIME(AFGBuildableSignSupport, mPoleScale);
}
void AFGBuildableSignSupport::PostLoadGame_Implementation(int32 saveVersion, int32 gameVersion){ Super::PostLoadGame_Implementation(saveVersion, gameVersion); }
void AFGBuildableSignSupport::SetPoleScale(const FVector2D& poleScale){ }
void AFGBuildableSignSupport::OnBuildEffectFinished(){ }
bool AFGBuildableSignSupport::CanBeSampled_Implementation() const{ return Super::CanBeSampled_Implementation(); }
struct FInstanceData AFGBuildableSignSupport::CreatePoleInstanceData(int32 variationIndex) const{ return Super::CreatePoleInstanceData(variationIndex); }
void AFGBuildableSignSupport::OnRep_PoleScale(){ }
